---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 3247980632-jNkBgYxbhvb3IIlhz6SPkJbNGswg1x6Afgbo7ZK
:access_token_secret: gburyUfO9dWNvhJ9WI4jNKFbWEoh3BSM1HjrV1xkzIpeB
